name: Remove old Docker images

on:
  push:
    branches: [ master ]

jobs:
  remove-old-docker-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get all Docker images
        run: docker images --all --format "{{.Repository}}:{{.Tag}}" > all_images.txt

      - name: Filter old Docker images
        run: |
          latest_images=$(cat all_images.txt | sort -r | uniq -c | sort | sed -n -e '1,3p' | cut -d" " -f2)
          old_images=$(grep -v "$latest_images" all_images.txt)

      - name: Remove old Docker images
        run: |
          for image in $old_images; do
            docker rmi --force "$image"
          done